import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState, useRef } from 'react';
import { QRCode } from 'react-qr-svg';
import styles from '../styles/Home.module.css';

export default function Home() {
	const [formStatus, setFormStatus] = useState(false);
	const [qrcode, setQrcode] = useState({
		timestamp: '',
		firstName: '',
		lastName: '',
		dob: '',
		phoneNumber: '',
		email: '',
		date: '',
	});

	const handleChange = () => (e) => {
		const name = e.target.name;
		const value = e.target.value;
		setQrcode((prevState) => ({
			...prevState,
			[name]: value,
		}));
	};

	const handleSubmit = (e) => {
		e.preventDefault();
		const dateTime = new Date();
		const newQrcode = {
			timestamp: dateTime.getTime(),
			firstName: qrcode['firstName'],
			lastName: qrcode['lastName'],
			dob: qrcode['dob'],
			phoneNumber: qrcode['phoneNumber'],
			email: qrcode['email'],
			date: dateTime.toISOString().replace(/T/, ' ').replace(/\..+/, ''),
		};

		console.log('newQrcode:', newQrcode);

		setQrcode(newQrcode);
		setFormStatus(true);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>QR Code Generator</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>QR Code Generator</h1>

				<p className={styles.description}>
					Generate QR Code With Personal Information
				</p>

				<form
					acceptCharset="UTF-8"
					method="POST"
					encType="multipart/form-data"
					id="ajaxForm"
					onSubmit={handleSubmit}
				>
					{/* First name */}
					<div className="form-group mb-2">
						<label htmlFor="inputFirstName">First name</label>
						<input
							type="text"
							className="form-control"
							id="inputFirstName"
							placeholder="Enter your first name"
							required
							name="firstName"
							value={qrcode.firstName}
							onChange={handleChange()}
						/>
					</div>

					{/* Last name */}
					<div className="form-group mb-2">
						<label htmlFor="inputLastName">Last name</label>
						<input
							type="text"
							className="form-control"
							id="inputLastName"
							placeholder="Enter your last name"
							required
							name="lastName"
							value={qrcode.LastName}
							onChange={handleChange()}
						/>
					</div>

					{/* Day of birth */}
					<div className="form-group mb-2">
						<label htmlFor="inputDob">Day of birth</label>
						<input
							type="date"
							className="form-control"
							id="inputDob"
							placeholder="Enter day of birth"
							required
							name="dob"
							value={qrcode.dob}
							onChange={handleChange()}
						/>
					</div>

					{/* Phone number */}
					<div className="form-group mb-2">
						<label htmlFor="inputPhoneNumber">Phone number</label>
						<input
							type="tel"
							className="form-control"
							id="inputPhoneNumber"
							placeholder="Enter phone number"
							required
							name="phoneNumber"
							value={qrcode.phoneNumber}
							onChange={handleChange()}
						/>
					</div>

					{/* Email */}
					<div className="form-group mb-2">
						<label htmlFor="inputEmail">Email</label>
						<input
							type="email"
							className="form-control"
							id="inputEmail"
							aria-describedby="emailHelp"
							placeholder="Enter email"
							required
							name="email"
							value={qrcode.email}
							onChange={handleChange()}
						/>
					</div>
					<hr />
					{formStatus ? (
						<div className="text-success mb-2">
							Your information has been sent.
						</div>
					) : (
						''
					)}
					<button type="submit" className="btn btn-primary">
						Submit
					</button>
				</form>

				<br />
				<br />

				<h1 style={{ float: 'right' }} className={styles.title}>
					QR code:
				</h1>

				<div style={{ textAlign: 'center', padding: '20px' }}>
					<QRCode
						bgColor="#FFFFFF"
						fgColor="#000000"
						level="Q"
						style={{ width: 256 }}
						value={JSON.stringify(qrcode)}
					/>
					<p style={{ marginTop: '20px' }}>id: {qrcode.timestamp}</p>
					<p>Create date: {qrcode.date}</p>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://frankie-tse-portfolio.netlify.app/"
					target="_blank"
					rel="noopener noreferrer"
				>
					Created by Frankie Tse
				</a>
			</footer>
		</div>
	);
}
